project_name: exocortex
builds:
  - main: main.go
    binary: exo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    hooks:
      pre: make pre-release
      post: make post-release
brew:
  github:
    owner: spencercdixon
    name: homebrew-formulae
  commit_author:
    name: Spencer Dixon
    email: spencercdixon@gmail.com
  folder: Formula
  homepage: "https://github.com/spencercdixon/exocortex"
  description: "A modern git based personal wiki"
  plist: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>KeepAlive</key>
      <true/>
      <key>Label</key>
      <string>#{plist_name}</string>
      <key>ProgramArguments</key>
      <array>
        <string>#{opt_bin}/exo</string>
        <string>start</string>
        <string>$EXO_WIKI</string>
      </array>
      <key>RunAtLoad</key>
      <true/>
      <key>WorkingDirectory</key>
      <string>#{HOMEBREW_PREFIX}</string>
      <key>StandardErrorPath</key>
      <string>#{var}/log/exocortex.log</string>
    </dict>
    </plist>
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
changelog:
  sort: asc
  filters:
    exclude:
      - '^Docs'
      - '^Refactor'
      - '^Removes'
